//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLine.Newtestgen180624
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Документ к модели.
    /// </summary>
    // *** Start programmer edit section *** (ДокументКМодели CustomAttributes)

    // *** End programmer edit section *** (ДокументКМодели CustomAttributes)
    [PublishName("DocumentToTheModel")]
    [ClassStorage("DocumentToTheModel")]
    [AutoAltered()]
    [Caption("Документ к модели")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДокументКМоделиE", new string[] {
            "Наименование as \'Наименование\'",
            "СсылкаНаФайл as \'Ссылка на файл\'"})]
    public class ДокументКМодели : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        private string fСсылкаНаФайл;
        
        private DataLine.Newtestgen180624.МодельОборудования fМодельОборудования;
        
        // *** Start programmer edit section *** (ДокументКМодели CustomMembers)

        // *** End programmer edit section *** (ДокументКМодели CustomMembers)

        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (ДокументКМодели.Наименование CustomAttributes)

        // *** End programmer edit section *** (ДокументКМодели.Наименование CustomAttributes)
        [PropertyStorage("Name")]
        [PublishName("Name")]
        [NotNull()]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (ДокументКМодели.Наименование Get start)

                // *** End programmer edit section *** (ДокументКМодели.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (ДокументКМодели.Наименование Get end)

                // *** End programmer edit section *** (ДокументКМодели.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокументКМодели.Наименование Set start)

                // *** End programmer edit section *** (ДокументКМодели.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (ДокументКМодели.Наименование Set end)

                // *** End programmer edit section *** (ДокументКМодели.Наименование Set end)
            }
        }
        
        /// <summary>
        /// СсылкаНаФайл.
        /// </summary>
        // *** Start programmer edit section *** (ДокументКМодели.СсылкаНаФайл CustomAttributes)

        // *** End programmer edit section *** (ДокументКМодели.СсылкаНаФайл CustomAttributes)
        [PropertyStorage("FileReference")]
        [PublishName("FileReference")]
        [NotNull()]
        public virtual string СсылкаНаФайл
        {
            get
            {
                // *** Start programmer edit section *** (ДокументКМодели.СсылкаНаФайл Get start)

                // *** End programmer edit section *** (ДокументКМодели.СсылкаНаФайл Get start)
                string result = this.fСсылкаНаФайл;
                // *** Start programmer edit section *** (ДокументКМодели.СсылкаНаФайл Get end)

                // *** End programmer edit section *** (ДокументКМодели.СсылкаНаФайл Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокументКМодели.СсылкаНаФайл Set start)

                // *** End programmer edit section *** (ДокументКМодели.СсылкаНаФайл Set start)
                this.fСсылкаНаФайл = value;
                // *** Start programmer edit section *** (ДокументКМодели.СсылкаНаФайл Set end)

                // *** End programmer edit section *** (ДокументКМодели.СсылкаНаФайл Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку DataLine.Newtestgen180624.МодельОборудования.
        /// </summary>
        // *** Start programmer edit section *** (ДокументКМодели.МодельОборудования CustomAttributes)

        // *** End programmer edit section *** (ДокументКМодели.МодельОборудования CustomAttributes)
        [Agregator()]
        [PublishName("EquipmentModel")]
        [NotNull()]
        [PropertyStorage(new string[] {
                "EquipmentModel"})]
        public virtual DataLine.Newtestgen180624.МодельОборудования МодельОборудования
        {
            get
            {
                // *** Start programmer edit section *** (ДокументКМодели.МодельОборудования Get start)

                // *** End programmer edit section *** (ДокументКМодели.МодельОборудования Get start)
                DataLine.Newtestgen180624.МодельОборудования result = this.fМодельОборудования;
                // *** Start programmer edit section *** (ДокументКМодели.МодельОборудования Get end)

                // *** End programmer edit section *** (ДокументКМодели.МодельОборудования Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокументКМодели.МодельОборудования Set start)

                // *** End programmer edit section *** (ДокументКМодели.МодельОборудования Set start)
                this.fМодельОборудования = value;
                // *** Start programmer edit section *** (ДокументКМодели.МодельОборудования Set end)

                // *** End programmer edit section *** (ДокументКМодели.МодельОборудования Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДокументКМоделиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДокументКМоделиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДокументКМоделиE", typeof(DataLine.Newtestgen180624.ДокументКМодели));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ДокументКМодели.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfДокументКМодели CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfДокументКМодели CustomAttributes)
    public class DetailArrayOfДокументКМодели : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (DataLine.Newtestgen180624.DetailArrayOfДокументКМодели members)

        // *** End programmer edit section *** (DataLine.Newtestgen180624.DetailArrayOfДокументКМодели members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ДокументКМодели by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ДокументКМодели.
        /// </summary>
        public DetailArrayOfДокументКМодели(DataLine.Newtestgen180624.МодельОборудования fМодельОборудования) : 
                base(typeof(ДокументКМодели), ((ICSSoft.STORMNET.DataObject)(fМодельОборудования)))
        {
        }
        
        public DataLine.Newtestgen180624.ДокументКМодели this[int index]
        {
            get
            {
                return ((DataLine.Newtestgen180624.ДокументКМодели)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(DataLine.Newtestgen180624.ДокументКМодели dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
